#!/bin/bash
sudo mkdir /jenkins
sudo cd /jenkins
sudo wget https://raw.githubusercontent.com/gowriand/jenkins/master/setupscripts/setupjenkins.sh
sudo sh -x setupjenkins.sh
echo "USE PASS to SETUP: "`cat /var/lib/jenkins/secrets/initialAdminPassword`

